#!/usr/bin/env bash
# This file installs Nginx with the required configurations
#then allow trafiic on prt 80 and crates a custom index page 

apt-get update -y
apt-get install nginx -y 


echo "Holberton School" > /var/www/html/index.html
nginx -s reload 2>/dev/null || service nginx start
