#!/usr/bin/env bash
apt-get update -y
apt-get install -y nginx

# Create the main page
echo "Holberton School" > /var/www/html/index.html

# Add redirect rule for /redirect_me
sed -i 's|location / {|location / {\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n|g' /etc/nginx/sites-available/default

# Restart nginx (no systemctl)
service nginx restart
